### ISSUE TITLE
Scene item properties not properly assigned in setProperties

### ISSUE THREAD

**Issue by Brendonovich** [Brendonovich/simple-obs#15]
JDude says this happens on animation, though tests show that setProperties does assign to the local values. Needs clarification.

**Comment by jdudetv** [comment]
Looks to just be width and height not updating. Position, rotation and scale are all working.

**Comment by Brendonovich** [comment]
> Looks to just be width and height not updating. Position, rotation and scale are all working.

Width and height cannot actually be set, neither can sourceWidth and sourceHeight, only scale.x and scale.y. Though, maybe we could calculate the appropriate scale given a desired width and height, derived from the source width and height?

**Comment by Brendonovich** [comment]
This is likely due to animating `width` and `height` of ColorSource. Not all sources have settings that influence the properties of the source, so an override of setSettings will be required in ColorSource and similar sources.
